'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlSubObjects

	'''<summary>
	'''RadTabStrip1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

	'''<summary>
	'''RadMultiPage1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

	'''<summary>
	'''RadPageView1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView

	'''<summary>
	'''lblSelectedTab control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSelectedTab As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ctrlCustomers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctrlCustomers As ctrlCustomers

	'''<summary>
	'''RadPageView2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView

	'''<summary>
	'''ctrlContacts control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctrlContacts As Global.Kolassa.DesignCenter.Web.UI.ctrlContacts

	'''<summary>
	'''RadPageView3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView

	'''<summary>
	'''ctrlImages control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctrlImages As ctrlImages

	'''<summary>
	'''RadComboBox1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadComboBox1 As Global.Telerik.Web.UI.RadComboBox

	'''<summary>
	'''RadAjaxPanel2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAjaxPanel2 As Global.Telerik.Web.UI.RadAjaxPanel

	'''<summary>
	'''RadTabStrip3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadTabStrip3 As Global.Telerik.Web.UI.RadTabStrip

	'''<summary>
	'''LoadingPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
End Class
