'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Default1

	'''<summary>
	'''RadMenu1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadMenu1 As Global.Telerik.Web.UI.RadMenu

	'''<summary>
	'''RadSkinManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadSkinManager1 As Global.Telerik.Web.UI.RadSkinManager

	'''<summary>
	'''RadAjaxManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager

	'''<summary>
	'''RadAjaxLoadingPanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel

	'''<summary>
	'''Image1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''rgMaster control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rgMaster As Global.Telerik.Web.UI.RadGrid

	'''<summary>
	'''RadGrid2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid

	'''<summary>
	'''ctrlSubObjects1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctrlSubObjects1 As ctrlSubObjects

	'''<summary>
	'''pnl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnl As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''Button1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''UpdateProgress1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

	'''<summary>
	'''odsContact control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsContact As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''odsContact0 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsContact0 As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''odsCustomer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsCustomer As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
