'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

	'''<summary>
	'''LoginView1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LoginView1 As Global.System.Web.UI.WebControls.LoginView

	'''<summary>
	'''ObjectDataSource1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''Repeater1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

	'''<summary>
	'''ctrlImages control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctrlImages As ctrlImages

	'''<summary>
	'''odsProjects control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents odsProjects As Global.System.Web.UI.WebControls.ObjectDataSource

	'''<summary>
	'''pnlDashboard control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDashboard As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''Button1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''ctrlGoogleChartPie control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ctrlGoogleChartPie As CtrlGoogleChartPie
End Class
