'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmIncompatMSG
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblEntityType_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEntityType_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLocation1_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation1_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCategory1_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategory1_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblClass1_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClass1_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescription1_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription1_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescription2_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription2_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel28 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txttxtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmbEntityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEntityType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEntityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntityID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLocation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocation1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLocation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocation2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCategory2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClass2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtModelOrStyle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelOrStyle1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtModelOrStyle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelOrStyle2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmbcboSeverity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboSeverity As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClass1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClass1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btncmdOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdOK As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btncmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbllblContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllblContinue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
