'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmIncompatibilities
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtIncompatibilityID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIncompatibilityID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblIncompatibilityID_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncompatibilityID_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboCategory1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbSeverity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSeverity As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblSeverity_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeverity_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlFrame16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrame16 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel17 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboEntityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboEntityType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboEntity As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlFrame18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrame18 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlFrame20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrame20 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel21 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboClass1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboClass1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btncmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btncmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btncmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmbcboRoom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboRoom1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboDescription1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboDescription1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboModelOrStyle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboModelOrStyle1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboCategory2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboCategory2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboClass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboClass2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboRoom2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboRoom2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboDescription2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboDescription2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbcboModelOrStyle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboModelOrStyle2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
