'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmLevels
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''cmbcboEntityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboEntityType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlFrame18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrame18 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlFrame20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrame20 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel21 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btncmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btncmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btncmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lstcboClass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboClass2 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txttxtNewLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtNewLevel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel37 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboDescription1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboDescription1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel39 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboModelOrStyle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboModelOrStyle1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel38 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboClass1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboClass1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel40 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btncmdResetStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdResetStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lstcboRoom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboRoom1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel42 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboCategory1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboCategory1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel41 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboEntity As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btncmdClearHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdClearHistory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
