'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmOptionPricing
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblUnitType_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnitType_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLocation_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocation_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRev_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRev_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDescription_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCustomerPrice_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerPrice_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUpgradeCat_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpgradeCat_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModel_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModel_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel26 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel27 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSearchLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearchLocation As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel34 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSearchUpgradeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearchUpgradeCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel35 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSearchUnitType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearchUnitType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel36 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSearchUpgradeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearchUpgradeLevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel37 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSearchOptionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearchOptionStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel33 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlBox38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBox38 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel39 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel40 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel41 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel42 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btncmdClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel46 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel47 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btncmdExplodeSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdExplodeSelections As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btncmdExcelExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdExcelExport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblLabel54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel54 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbSearchDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSearchDescription As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel56 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPricingRevNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPricingRevNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCustomerPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtUpgradeOptionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUpgradeOptionID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmbUnitType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUnitType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLocation As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtModelOrStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelOrStyle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmbOptionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbOptionStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cmbBuildingPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBuildingPhase As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbLeadVendor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLeadVendor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbUpgradeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUpgradeCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbUpgradeLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUpgradeLevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkStandard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStandard As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtDeveloperPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeveloperPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btncmdOptionDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncmdOptionDetails As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtAdditionalFileToPrint1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditionalFileToPrint1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
