'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmQuote2
    
    '''<summary>
    '''frmtest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmtest As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''pnlCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCalendar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mCalendar As Global.System.Web.UI.WebControls.Calendar
    
    '''<summary>
    '''DD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuote As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''DetailsView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailsView2 As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''FormView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormView1 As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''rblPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblPhase As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lstRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRooms As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''updpnlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlCategory As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lstClasses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstClasses As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''updpnlLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlLevels As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lstUpgradesAvail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstUpgradesAvail As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''cmdAddNewOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddNewOption As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdSearchQuotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSearchQuotes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdAutoPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAutoPick As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdMissingSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMissingSelections As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdCommunications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCommunications As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPayments As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAdjustments As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdCustomerReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCustomerReceipt As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updpnlStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlStyle As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStyle As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lstStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstStyle As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''updprogStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updprogStyle As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''updpnlRequestedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlRequestedUpgrades As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlRequestedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequestedUpgrades As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lstSelectedUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSelectedUpgrade As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''UpdateProgress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress3 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''updpnlReqUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updpnlReqUpgrades As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlReqUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReqUpgrades As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lstRequestedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRequestedUpgrades As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''UpdateProgress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress2 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''odsCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCategories As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRooms As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsQuotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsQuotes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsQuoteStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsQuoteStatus As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsPhase1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPhase1Status As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsPhase2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPhase2Status As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsLevels As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsStyle As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''litMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''odsRequestedUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRequestedUpgrade As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsRequestedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRequestedUpgrades As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsMissing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMissing As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
