'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmReportManagerMaintenance
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtReportDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtReportID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlsubReportCategoryMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlsubReportCategoryMap As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblsubReportCategoryMap_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsubReportCategoryMap_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlsubReportFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlsubReportFields As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblsubReportFields_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsubReportFields_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtcboReportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcboReportName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel0 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRequired_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequired_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
