'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmReportManager
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnCmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCmdClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCmdrunreport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCmdrunreport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lstlstReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstlstReports As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlfraReportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlfraReportType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rbnOptPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbnOptPreview As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rbnOptPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbnOptPrint As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rbnOptFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbnOptFile As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboReportCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboReportCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblReportCategoryDescription_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportCategoryDescription_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboCustomerName As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel52 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txttxtDateStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtDateStart As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel60 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txttxtDateEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtDateEnd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel62 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboBuildingPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboBuildingPhase As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel68 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboFloorStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboFloorStart As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel72 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboCommunicationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboCommunicationType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel80 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboUpgradeCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboUpgradeCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel82 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboPurchaseStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboPurchaseStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel84 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel84 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboOptionGrouping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboOptionGrouping As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel86 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboFloorEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboFloorEnd As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel90 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel90 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtReportComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReportComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txttxtHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtHeading As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLabel94 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel94 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbcboLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbcboLocation As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblLabel96 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel96 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboUnitNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboUnitNumber As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel64 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lstcboUnitType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstcboUnitType As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblLabel66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabel66 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
