'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmRoomUpgradesAvailable
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtRoomTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoomTypeID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRoomTypeID_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoomTypeID_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbUnitTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUnitTypeID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblUnitTypeID_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnitTypeID_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRoomName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoomName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRoomName_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoomName_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRoomDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRoomDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblRoomDescription_Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRoomDescription_Label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnltblRoomUpgrades_subform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnltblRoomUpgrades_subform As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenerated As Global.System.Web.UI.WebControls.Label
End Class
