<%@ Page Language="vb" EnableEventValidation=false AutoEventWireup="false" MasterPageFile="~/Site.master" CodeBehind="frmUnitTypes.aspx.vb"  Inherits="frmUnitTypes"%>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<%@ Register src="ReportManager/ReportContainer.ascx" tagname="ReportContainer" tagprefix="uc1" %>
<%@ Register assembly="System.Web.Extensions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI" tagprefix="asp" %>




<asp:Content ID=Content1 runat=server ContentPlaceHolderID="MainContent" >



  

        <asp:Panel ID="Panel2" BackColor=Bisque runat="server" CssClass="collapsePanelHeader" Height="30px"> 
            <div style="padding:5px; cursor: pointer; vertical-align: middle;">
                <div style="float: left;"></div>
                <div style="float: left; margin-left: 20px;">
                    <asp:Label ID="Label2" runat="server"></asp:Label>  
          
    <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
                </div>
                <div style="float: right; vertical-align: middle;">
                    <asp:ImageButton ID="Image1" runat="server" ImageUrl="~/images/expand_blue.jpg" AlternateText="(Show Details...)"/>
                </div>
            </div>
        </asp:Panel>
   
      
 <cc1:CollapsiblePanelExtender ID="cpe" runat="Server"
    TargetControlID="Panel1"
    CollapsedSize="0"
    
    Collapsed="True"
    ExpandControlID="Panel2"
    CollapseControlID="Panel2"
    AutoCollapse="False"
    AutoExpand="False"
    ScrollContents="True"
    TextLabelID="Label1"
    CollapsedText="Show Filter..."
    ExpandedText="Hide Filter" 
    ImageControlID="Image1"
    ExpandedImage="~/images/expand.jpg"
    CollapsedImage="~/images/collapse.jpg"
    ExpandDirection="Vertical" />
   
    <asp:Panel ID="Panel1" runat="server" >
        <!-- <uc1:ReportContainer ID="ReportContainer1" runat="server" 
         ReportCategoryType="frmVendors"  /> -->
    <asp:Button ID="cmdRunReport" runat="server" Text="Filter" /><br />
    <asp:Literal ID="litMsg" runat="server"></asp:Literal><br />
       
    </asp:Panel>

<table><tr><td>
    <asp:Literal ID="Literal1" runat="server" Text="Records Per Page  "></asp:Literal>


    <asp:DropDownList ID="ddlPagelength" runat="server" AutoPostBack="True">
    <asp:ListItem Text='10' Value="10" />
    <asp:ListItem Text='20' Value="20" />
    <asp:ListItem Text='50' Value="50" />
    </asp:DropDownList>
</td><td>
 <asp:Literal ID="Literal2" runat="server" Text="Actions  "></asp:Literal>


    <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True">
        <asp:ListItem Text='[Select One]' Value="SelectOne" />
        <asp:ListItem Text='Export To Excel' Value="ExportToExcel" />
    </asp:DropDownList>
</td></tr></table>



    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate> 

            <asp:gridview id="DataGridDisplay" runat="server" DataSourceID="ObjectDataSource1"
                AutoGenerateDeleteButton="True" 
                DataKeyNames="UnitTypeID" 
                AutoGenerateEditButton="True"
                 CsssClass="GridView" 
                CssClass="table table-striped table-bordered table-hover"
                 GridLines="Vertical" AllowPaging="True" 
                AllowSorting="True" AutoGenerateColumns="False">           
                <FooterStyle CssClass="FooterStyle" />
                <RowStyle CssClass="RowStyle"  />            
               <Columns>
                    <asp:Templatefield HeaderText="ID" SortExpression="UnitTypeID">          
                        <itemTemplate>
                            <asp:Literal id="UnitTypeID" runat="server"  Text='<%# Container.DataItem("UnitTypeID") %>'  />
                        </ItemTemplate>                  
                    </asp:TemplateField>
  
                 <asp:TemplateField HeaderText="Name" SortExpression="UnitTypeName">
                        <FooterTemplate>
                            <asp:TextBox id="UnitTypeName" MaxLength=50 runat="server" Text='<%# bind("UnitTypeName") %>'/>
                         <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="UnitTypeName" ErrorMessage="* Required Field" ></asp:RequiredFieldValidator>
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="UnitTypeName" MaxLength=50 runat="server" Text='<%# Container.DataItem("UnitTypeName") %>'/>
                        </EditItemTemplate>
                        <itemTemplate>
                            <asp:Literal id="UnitTypeName" runat="server"  Text='<%# Container.DataItem("UnitTypeName") %>'  />
                        </ItemTemplate>             
                    </asp:TemplateField>
                    
                    <asp:TemplateField HeaderText="Unit Type Description" SortExpression="UnitTypeDescription">
                        <FooterTemplate>
                            <asp:TextBox id="UnitTypeDescription" MaxLength=50 runat="server" Text='<%# Bind("UnitTypeDescription") %>'/>
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="UnitTypeDescription" MaxLength=50 runat="server" Text='<%# Container.DataItem("UnitTypeDescription") %>'/>
                        </EditItemTemplate>
                         <itemTemplate>
                            <asp:Literal id="UnitTypeDescription" runat="server"  Text='<%# Container.DataItem("UnitTypeDescription") %>'  />
                        </ItemTemplate>
                    </asp:TemplateField>
                    
                    <asp:TemplateField HeaderText="Sub-Type" SortExpression="SubType">
                        <FooterTemplate>
                            <asp:TextBox id="SubType" MaxLength=5 runat="server" Text='<%# Bind("SubType") %>'/>
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="SubType" MaxLength=5 runat="server" Text='<%# Container.DataItem("SubType") %>'/>
                        </EditItemTemplate>
                         <itemTemplate>
                             <asp:Literal id="SubType" runat="server"  Text='<%# Container.DataItem("SubType") %>'  />
                        </ItemTemplate>
                     </asp:TemplateField>   
               
                     <asp:TemplateField HeaderText="Level" SortExpression="Level">
                        <FooterTemplate>
                            <asp:TextBox id="Level" MaxLength=5 runat="server" Text='<%# Bind("Level") %>'/>
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="Level" MaxLength=5 runat="server" Text='<%# Container.DataItem("Level") %>'/>
                        </EditItemTemplate>
                         <itemTemplate>
                             <asp:Literal id="Level" runat="server"  Text='<%# Container.DataItem("Level") %>'  />
                        </ItemTemplate>
                     </asp:TemplateField>   
                     
                         <asp:TemplateField HeaderText="Model Unit" SortExpression="ModelUnit">
                        <FooterTemplate>
                            <asp:TextBox id="ModelUnit" MaxLength=5 runat="server" Text='<%# Bind("ModelUnit") %>'/>
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:TextBox id="ModelUnit" MaxLength=5 runat="server" Text='<%# Container.DataItem("ModelUnit") %>'/>
                        </EditItemTemplate>
                         <itemTemplate>
                             <asp:Literal id="ModelUnit" runat="server"  Text='<%# Container.DataItem("ModelUnit") %>'  />
                        </ItemTemplate>
                     </asp:TemplateField>                         
                    
                    <asp:TemplateField HeaderText="Active" SortExpression="Active">
                 <FooterTemplate>
                           <asp:Button ID="cmdAdd" Text="Add" runat="server" onclick="cmdAdd_Click"/>
                        </FooterTemplate>
                        <EditItemTemplate>
                            <asp:CheckBox id="chkActive" runat=server Checked='<%# Container.DataItem("Active") %>' />
                        </EditItemTemplate>
                         <itemTemplate>
                            <asp:Literal id="litActive" runat="server"  Text='<%# Container.DataItem("Active") %>'  />
                        </ItemTemplate>
                    </asp:TemplateField>
                    
                    
   
                </Columns>

            </asp:gridview>
           <asp:Button ID="cmdAddNew" Text="Add New Record" runat="server"/>
  </ContentTemplate>
  
        
        <triggers>
            <asp:AsyncPostBackTrigger ControlID="ddlPagelength" 
                EventName="SelectedIndexChanged" />
            <asp:AsyncPostBackTrigger ControlID="cmdAddNew" EventName="Click" />
            <asp:AsyncPostBackTrigger ControlID="cmdRunReport" EventName="Click" />
        </triggers>
  
        
    </asp:UpdatePanel>
    <asp:UpdateProgress runat= server ID="UP1" AssociatedUpdatePanelID="UpdatePanel1">
        <ProgressTemplate >
                                <div id="OuterTableCellOverlay">
                            <div id="InnerTableCellOverlay">
                                <b>... Please Wait ...</b>
                             
                               
            <asp:Image ID="LoadImage" runat="server" ImageUrl="images/loading.gif" />
                            </div>
                        </div>
           </ProgressTemplate>
    </asp:UpdateProgress>
<br />


    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" 
    SelectMethod="LoadUnitTypes" TypeName="clsSelectDataLoader" 
        DeleteMethod="DeleteUnitTypes" InsertMethod="InsertUnitTypes">
      
        <SelectParameters>
              <asp:SessionParameter DefaultValue="1" Name="llNodeID" SessionField="NodeID"                 Type="Int64" />
              <asp:SessionParameter  Name="lsWhere"     SessionField="msFilter" Type="String" />
              <asp:Parameter DefaultValue="True" Name="lbActive" Type="Boolean" />
              <asp:Parameter DefaultValue="0" Name="llID" Type="Int64" />
        </SelectParameters>
        <InsertParameters>
            <asp:sessionParameter Name="llNodeID" Type="Int64" SessionField="NodeID" DefaultValue="1"  />
            <asp:ControlParameter Name="lsUnitTypeName"   ControlID="DataGridDisplay" Type="String"  PropertyName="SelectedValue" />
            <asp:ControlParameter Name="lsUnitTypeDescription" ControlID="DataGridDisplay"   Type="String" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="lsSubType" ControlID="DataGridDisplay"  Type="String" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="lsLevel" ControlID="DataGridDisplay"   Type="String" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="lsModelUnit" ControlID="DataGridDisplay"  Type="String" PropertyName="SelectedValue" />
        </InsertParameters>
        

        
        <DeleteParameters>
            <asp:Parameter Name="UnitTypeID" Type="Int64" />
        </DeleteParameters>
        

        
</asp:ObjectDataSource>

    </asp:Content>