Imports Telerik.Web.UI
Public Class Logins
    Inherits System.Web.UI.Page
    Protected Sub RadGrid_ItemCreatedw(sender As Object, e As GridItemEventArgs)
        '     TryCast(Me.RadGrid1.MasterTableView.AutoGeneratedColumns(0), GridBoundColumn).MaxLength = 5
        Dim item As GridEditableItem = TryCast(e.Item, GridEditableItem)
        If item IsNot Nothing AndAlso e.Item.IsInEditMode AndAlso e.Item.ItemIndex <> -1 Then
            TryCast(item.EditManager.GetColumnEditor("ID").ContainerControl.Controls(0), TextBox).Enabled = False
        End If
    End Sub











    Private Sub rgMaster_ItemDataBound(sender As Object, e As GridItemEventArgs) Handles rgMaster.ItemDataBound
        FillStates(e)
    End Sub
    Private Sub FillStates(e As GridItemEventArgs)
        If e.Item.IsInEditMode Then
            Dim t As String = e.Item.GetType.ToString
            If t = "Telerik.Web.UI.GridEditFormItem" Then
                Dim editform As GridEditFormItem = e.Item
                Dim r As RadDropDownTree = editform.FindControl("rddtCountry")
                If Not r Is Nothing Then
                    If r.DataFieldID Is Nothing Then
                        r.DataFieldID = "LookupID"
                        r.DataFieldParentID = "NodeID"
                        r.DataValueField = "LookupValue"
                        r.DataTextField = "LookupDescription"
                        r.DataSource = GetCountriesandProvince()
                        r.DataBind()
                    End If
                End If
            End If
        End If
    End Sub

    Protected Sub Page_PreRender(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.PreRender
        If rgMaster.SelectedIndexes.Count = 0 Then
            rgMaster.SelectedIndexes.Add(0)
        End If

    End Sub








    Public Function GetCountriesandProvince() As DataTable


        Dim t, table As New DataTable()
        If 1 = 1 Then
            Dim lu As clsLookups = New clsLookups
            table = lu.GetRecords("", "", "Countries", 0, 0).Tables(0)
            t = lu.GetRecords("", "", "StateProvince", 0, 0).Tables(0)
            table.Merge(t)

        Else
            table.Columns.Add("LookupID")
            table.Columns.Add("NodeID")
            table.Columns.Add("LookupValue")
            table.Columns.Add("LookupDescription")

            table.Rows.Add(New [String]() {"1", Nothing, "World_Continents", "World Continents"})
            table.Rows.Add(New [String]() {"2", Nothing, "World_Oceans", "World Oceans"})

            table.Rows.Add(New [String]() {"3", "1", "Asia", "Asia"})
            table.Rows.Add(New [String]() {"4", "1", "Africa", "Africa"})
            table.Rows.Add(New [String]() {"5", "1", "Australia", "Australia"})
            table.Rows.Add(New [String]() {"6", "1", "Europe", "Europe"})
            table.Rows.Add(New [String]() {"7", "1", "North_America", "North America"})
            table.Rows.Add(New [String]() {"8", "1", "South_America", "South America"})

            table.Rows.Add(New [String]() {"9", "2", "Arctic_Ocean", "Arctic Ocean"})
            table.Rows.Add(New [String]() {"10", "2", "Atlantic_Ocean", "Atlantic Ocean"})
            table.Rows.Add(New [String]() {"11", "2", "Indian_Ocean", "Indian Ocean"})
            table.Rows.Add(New [String]() {"12", "2", "Pacific_Ocean", "Pacific Ocean"})
            table.Rows.Add(New [String]() {"13", "2", "South_Ocean", "SouthOcean"})

        End If
        Return table
    End Function

    Protected Sub ddlStateProvince_DataBinding(sender As Object, e As EventArgs)
        Dim ddList As DropDownList = CType(sender, DropDownList)
        RemoveHandler ddList.DataBinding, AddressOf ddlStateProvince_DataBinding
        Try
            ddList.DataBind()
        Catch ex As ArgumentOutOfRangeException
            ddList.SelectedValue = ""  ' or whatever value you have for the page dropdownlist
        End Try
    End Sub

    '  Protected Sub rgMaster_ItemCommand(sender As Object, e As GridCommandEventArgs) Handles rgMaster.ItemCommand
    '        RadGrid2.SelectedIndexes.Clear()
    '  End Sub
    Private Sub Page_Load(sender As Object, e As System.EventArgs) Handles MyBase.Load

        Dim rg As RadGrid = rgMaster
        Dim gtv As GridTableView
        Dim gdi As GridDataItem
        Dim r As RadDropDownTree = Nothing
        Dim childItem As GridNestedViewItem


        For Each gdi In rgMaster.MasterTableView.Items
            If Not gdi.ChildItem Is Nothing Then
                gtv = gdi.ChildItem.NestedTableViews(0)
                For Each childItem In gtv.GetItems(GridItemType.NestedView)
                    r = childItem.FindControl("rddtCountry")
                Next

                If Not r Is Nothing Then
                    r.DataFieldID = "LookupID"
                    r.DataFieldParentID = "NodeID"
                    r.DataValueField = "LookupValue"
                    r.DataTextField = "LookupDescription"
                    r.DataSource = GetCountriesandProvince()
                    r.DataBind()
                End If

            End If
        Next

        If Not (LatestLoadedControlName Is Nothing) Then
            LoadUserControl(LatestLoadedControlName)
        Else
            Me.RadTabStrip1.SelectedIndex = 1
            LoadUserControl("ctrlContactEntry.ascx")
        End If
    End Sub

    Private Sub lblContacts_Click(sender As Object, e As System.EventArgs)
        LoadUserControl("ctrlContactEntry.ascx")
    End Sub

    Private Sub lblDetails_Click(sender As Object, e As System.EventArgs)
        LoadUserControl("CtrlCustomers.ascx")
    End Sub

    Private Sub lblImages_Click(sender As Object, e As System.EventArgs)

    End Sub

    Public Sub LoadUserControl(controlName As String)
        If controlName = "ctrlImages.ascx" Then
            'ctrlImageNew1.Visible = True
        Else
            '    ctrlImageNew1.Visible = False
        End If
        If Not (LatestLoadedControlName Is Nothing) Then
            Dim previousControl As Control = Panel1.FindControl(LatestLoadedControlName.Split("."c)(0))
            If Not (previousControl Is Nothing) Then
                Me.Panel1.Controls.Remove(previousControl)
            End If
        End If
        Dim userControlID As String = controlName.Split("."c)(0)
        Dim targetControl As Control = Panel1.FindControl(userControlID)
        If targetControl Is Nothing Then
            Dim userControl As UserControl = CType(Me.LoadControl(controlName), UserControl)
            'slashes and tildes are forbidden
            userControl.ID = userControlID.Replace("/", "").Replace("~", "")
            Me.Panel1.Controls.Add(userControl)
            LatestLoadedControlName = controlName
        End If
    End Sub





    Private Property LatestLoadedControlName() As String
        Get
            Return CStr(ViewState("LatestLoadedControlName"))
        End Get
        Set(value As String)
            ViewState("LatestLoadedControlName") = value
        End Set
    End Property

    Protected Sub rgMaster_SelectedIndexChanged(sender As Object, e As EventArgs) Handles rgMaster.SelectedIndexChanged
        Dim ls As String = LatestLoadedControlName
        Select Case ls
            Case "ctrlImages.ascx", "ctrlContacts.ascx", "ctrlCustomers.ascx", "ctrlContactEntry.ascx"
            Case Else
                Exit Sub
        End Select
        LoadUserControl(ls)

    End Sub

    Private Sub rgMaster_ItemUpdated(sender As Object, e As GridUpdatedEventArgs) Handles rgMaster.ItemUpdated

    End Sub



    Protected Sub RadTabStrip1_TabClick(sender As Object, e As RadTabStripEventArgs) Handles RadTabStrip1.TabClick
        Dim lsTab As String = e.Tab.Text
        Dim ls As String = ""
        Select Case lsTab
            Case "Details"
                ls = "ctrlCustomers.ascx"
            Case "Images"
                ls = "ctrlImages.ascx"
            Case "Contacts"
                ls = "ctrlContactEntry.ascx"
            Case Else
                Exit Sub
        End Select
        LoadUserControl(ls)
    End Sub
End Class