<%@ Page Title="About" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.vb" Inherits="Kolassa.DesignCentre.UI.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <p>Design Centre.</p>
    <p>Design Centre gives Building Owners the power to maximize profits and ensure completeness during the sales phase.  With Design Centre, sales assiciates 
		will be guided through all upgrade choices with a consolidated view of ALL the options for their unit.  This ensures that Sales Assiciates have the tools 
		they need to fully complete the unit sale.

	Custom Reports can be produced to provide lists of missing categories, ensuring all options have been selected.  This single source of truth enables the sales team 
		to help customers find all the options they like.  

		Customer Receipts, product documentation, build schedules, selection lists are just some of the reports that can be generated by the Design Center application.  

		Owners can have piece of mind knowing that Design Centre is tracking the key items owners need to provide customers the best experience possible.
    </p>
</asp:Content>
