'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmQuote

    '''<summary>
    '''odsQuotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsQuotes As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRooms As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCategories As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsQuoteStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsQuoteStatus As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsPhase1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPhase1Status As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsPhase2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPhase2Status As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsLevels As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsStyle As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsSelectedUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSelectedUpgrade As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsRequestedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRequestedUpgrades As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsMissing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsMissing As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lblQuoteForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuoteForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litID As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litPageInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPageInfo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMsg As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''pnlButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlQuoteLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuoteLookup As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ctrlQuoteLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlQuoteLookup As Global.Kolassa.DesignCentre.UI.ctrlQuoteLookup

    '''<summary>
    '''pnlCommunications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCommunications As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ctrlCommunications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlCommunications As Global.Kolassa.DesignCentre.UI.ctrlCommunications

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CtrlAdjustments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CtrlAdjustments As Global.Kolassa.DesignCentre.UI.ctrlAdjustments

    '''<summary>
    '''pnlSelectedItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectedItems As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtItemText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSelectedItemID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectedItemID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtItemPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdjustment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTotalPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdSelectedItemSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSelectedItemSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPayments As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ctrlPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlPayments As Global.Kolassa.DesignCentre.UI.ctrlPayments

    '''<summary>
    '''pnlQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuote As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdAddNewOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddNewOption As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdAutoPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAutoPick As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnAutoPop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutoPop As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReports As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdMissingSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMissingSelections As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdCustomerReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCustomerReceipt As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdStandardReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdStandardReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdVendorInstallationReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdVendorInstallationReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''fvQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvQuote As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''upPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPhase As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''odsPhases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsPhases As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''grdPhases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPhases As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlPhaseEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPhaseEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtPhaseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhaseName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPhaseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhaseID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlPhaseStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPhaseStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTargetDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTargetDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompleteDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdPhaseStatusSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPhaseStatusSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upprogPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upprogPhase As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''rblPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblPhase As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlLoca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLoca As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upRoom As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstRooms2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRooms2 As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lstRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRooms As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updPnlCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPnlCategories As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lvCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvCategories As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lstCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCategories As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''updPrgCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPrgCategories As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''updPnlLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPnlLevels As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lstLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstLevels As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''updPrgLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPrgLevel As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''updPnlOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPnlOptions As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblAvailableUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvailableUpgrades As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStyle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstStyle As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''updPrgOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPrgOptions As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''updPnlSelectedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPnlSelectedUpgrades As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSelectedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedUpgrades As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSelectedUpgrades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectedUpgrades As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstSelectedUpgrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstSelectedUpgrade As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''updPrgSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPrgSelected As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''lblCustId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustId1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtId1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContact1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContact1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustId2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustId2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtId2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtId2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContact2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContact2 As Global.System.Web.UI.WebControls.TextBox
End Class
