'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmReports

    '''<summary>
    '''lnkGetWhereClause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGetWhereClause As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgLoadColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLoadColumns As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnkdPrintPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkdPrintPage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkPrintAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPrintAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ReportContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportContainer1 As Global.Kolassa.DesignCenter.ReportManager.ReportContainer

    '''<summary>
    '''uppnlReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uppnlReport As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblModalTitleColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalTitleColumns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModalBodyColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalBodyColumns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctrlReportColumns1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlReportColumns1 As Global.Kolassa.DesignCenter.ReportManager.ctrlReportColumns

    '''<summary>
    '''lblModalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblModalBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalBody As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ReportResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportResults As Global.Kolassa.DesignCenter.ReportManager.ReportResults
End Class
