'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewQuote
    
    '''<summary>
    '''lblNewQuoteTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewQuoteTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litQuoteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litQuoteID As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblSelectaProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectaProject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProject As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litProjectID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProjectID As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblSelectaUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectaUnit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUnit As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litUnitID As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblSelectCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectCustomer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCustomerName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCustomerID As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cmdCreateQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCreateQuote As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlProjectLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProjectLookup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrlProjectListQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlProjectListQuote As Global.Kolassa.DesignCentre.UI.ctrlProjectList
    
    '''<summary>
    '''pnlQuoteLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuoteLookup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrlUnitList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlUnitList1 As Global.Kolassa.DesignCentre.UI.ctrlUnitList
    
    '''<summary>
    '''pnlCustomerLookup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomerLookup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ctrlCustomerList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlCustomerList1 As Global.Kolassa.DesignCentre.UI.ctrlCustomerList
    
    '''<summary>
    '''pnlSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSuccess As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSuccess As Global.System.Web.UI.WebControls.Literal
End Class
